services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: airo_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html/api
    depends_on:
      - database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: airo_client
    tty: true
    ports:
      - "4200:4200"
      - "9876:9876"
    volumes:
      - ./client:/var/www/html/client

  nginx:
    image: nginx
    container_name: airo_nginx
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html
    depends_on:
      - api
      - client

  database:
    image: mariadb:11.7.2
    container_name: airo_db
    environment:
      MYSQL_DATABASE: airo
      MYSQL_USER: airo
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
